### ISSUE TITLE
Configuring globalSetup to only run once in jest watch mode

### ISSUE THREAD

**Issue by jbmusso** [ForbesLindesay/atdatabases#120]
Greetings, thanks for the great `@database` packages.

I'm currently experimenting with jest and PostgreSQL, and the test setup detailed in the documentation works great (https://www.atdatabases.org/docs/pg-test).

At the moment, `jest` runs the `globalSetup` script everytime the tests are executed in watch mode (see: https://github.com/facebook/jest/issues/6800), rather than once on start. This is a bit costly and slows down the iteration/feedback loop when developing. Depending on the case, this may or may not be desireable behavior.

According to the above `jest` issue, this setting could be configured at the jest level. It appears that the solution currently needs to be implemented in the script which does perform the `globalSetup`, [by checking the watch and watchAll properties](https://github.com/facebook/jest/issues/6800#issuecomment-439969465).

This feature is not yet supported by `jest`, though it could/should (?).

What would you think about adding this to `@databases/pg-test`? I'm unsure about the API (environment variable?) but I may have some time to work on a PR.

**Comment by ForbesLindesay** [comment]
You can achieve this via the CLI:

```
pg-test run -- jest --watch
```

It's not the default in part because re-using the same database across multiple test runs is likely to result in test failures. It's better practice (albeit a little bit slower) to always start with a fresh database for each run, even in watch mode.

One thing that can speed up tests in watch mode significantly is splitting out your tests into "projects" so the test database is only started for tests that actually require a database. e.g. https://github.com/ForbesLindesay/atdatabases/blob/a610ebd6cf7245bec717ff9f311c357cec76ee6e/package.json#L28-L50
