### ISSUE TITLE
Improved Queryable?

### ISSUE THREAD

**Issue by OmgImAlexis** [ForbesLindesay/atdatabases#139]
I wanted to get your thoughts on this change before I open a PR.

https://github.com/ForbesLindesay/atdatabases/blob/2830a3e9d8a3beaffa56438f47ad701f0b4a261f/packages/pg/src/types/Queryable.ts#L15-L20

```ts
  query<T = any>(query: SQLQuery): Promise<T[]>;
  query<T = any>(query: SQLQuery[]): Promise<T[][]>;
  queryStream<T = any>(query: SQLQuery, { batchSize, signal }: {
      batchSize?: number;
      signal?: AbortSignal;
  }): AsyncIterable<T>;
```

**Comment by ForbesLindesay** [comment]
I think it adds a false sense of security. There's no genuine type safety being added because the `T` does not appear anywhere in the parameters to `.query`. You can get equivalent type safety by doing `const results: T[] = await db.query(q)`.

There is an API with genuine type safety, but I haven't had time to write docs yet:

- https://github.com/ForbesLindesay/atdatabases/tree/master/packages/pg-typed
- https://github.com/ForbesLindesay/atdatabases/tree/master/packages/pg-schema-cli

**Comment by ForbesLindesay** [comment]
The type safe API is now documented.
