### ISSUE TITLE
unterminated dollar-quoted string at or near "$$

### ISSUE THREAD

**Issue by mklimkin0190** [ForbesLindesay/atdatabases#170]
I'm using `@databases/pg`. I recently upgraded to 5.1.0 from 2.3.0, and started getting this error on function creation.

Here's my setup (simplified):

```javascript
export default class Migration {
  static dbConnection: ConnectionPool

  runSingleUpMigration = async () => {
    const migration = sql.file('<path_to_sql_file>')
    await Migration.dbConnection.query(migration)
  }
}
```

SQL file:

```sql
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER <trigger_name> BEFORE UPDATE ON <table_name> FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
```

The error:

```
unterminated dollar-quoted string at or near "$$
BEGIN
    NEW.updated_at = now()"

  1 | CREATE OR REPLACE FUNCTION update_updated_at_column()
> 2 | RETURNS TRIGGER AS $$
    |                    ^
  3 | BEGIN
  4 |     NEW.updated_at = now()
```

Would appreciate any help here!

Update: replacing `$$` with single quotes is a workaround, but it still looks like a bug: $$ is a valid SQL syntax. and should be supported.

**Comment by clafollett** [comment]
We've recently started a new project which will be utilizing AWS's Aurora Postgres cluster with lambda gql apis on top of it. I selecting `@databases/pg` for our DB API but this is proving to be a bit of a pain too. I ran into this issue when trying to create procedures.

Thanks for the tip on quoting the proc bodies @mklimkin0190. 👍 🥇 

I'm a life long MS SQL Server guy. We have made the business decision to convert to PG to save some $$$ and for the additional functionality not in MSSQL. The syntax of `quoting` the procedure body is a feature I was not aware of. I checked the docs to understand what you were saying. There are some nice options for defining the body! My only other thought was to do some SQL Server `sp_execute_sql` stored proc type call and passing our script file contents for the `@command` param.

**Comment by ForbesLindesay** [comment]
Ah, this sucks. Thanks for raising the issue.

This is a bug in [split-sql-query](https://github.com/ForbesLindesay/atdatabases/tree/master/packages/split-sql-query) that's causing it to split your create function call into multiple statements when it sees the `;`. I'll update it to support treating `$$` as quotes as per https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

In the mean time, you could use `'` instead of `$$` for simple examples.

**Comment by clafollett** [comment]
> Ah, this sucks. Thanks for raising the issue.
> 
> This is a bug in [split-sql-query](https://github.com/ForbesLindesay/atdatabases/tree/master/packages/split-sql-query) that's causing it to split your create function call into multiple statements when it sees the `;`. I'll update it to support treating `$$` as quotes as per https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING
> 
> In the mean time, you could use `'` instead of `$$` for simple examples.

Thank you sir! Yup, single quoting the contents worked just fine. It just added an extra minute to copy my working scripts into my deployment script and then doubling up on any embedded single quotes. Easy enough with a search and replace in selected text. I'll look forward to the fix though! My deployments are working with this work around though so I'm happy.

Otherwise, I love this library. It's a very simple, easy to use query mechanism. I'm working on adding a generic's typing pattern in my consumer to make my access a bit more type safe.

**Comment by ForbesLindesay** [comment]
That's great to hear. Thank you.

In case you missed it, we do have some support for generating (and using) TypeScript types from the postgres schema: https://www.atdatabases.org/docs/pg-guide-typescript
