### ISSUE TITLE
Ability to pass in `pg` construction method

### ISSUE THREAD

**Issue by BBB** [ForbesLindesay/atdatabases#172]
Hi @ForbesLindesay, 

I'd like to be able to pass in a constructor for how to create the `pg` client/ pool. This is in order to support tracing via. https://github.com/openzipkin/zipkin-js/tree/master/packages/zipkin-instrumentation-postgres

Would you be open to accepting this as a PR?

Thanks for the fantastic lib!

**Comment by ForbesLindesay** [comment]
Hi @BBB, I'm afraid I don't want to accept this change. It would tie @databases far too closely to a single implementation of the postgres client. We actually replaced the entire Postgres client recently with very minimal breaking changes, in part because our API does not expose low level details of the underlying driver.

We do support a few utilities to help with traceability.  These helpers are also available on our other clients (e.g. MySQL).

https://www.atdatabases.org/docs/pg-guide-logging
